### ISSUE TITLE
/opt/harbor/common/templates/nginx/nginx.http.conf &  /opt/harbor/common/templates/nginx/nginx.https.conf dont exists on a clean install

### ISSUE THREAD

**Issue by huckley** [bodsch/ansible-role-harbor#3]
Hello, I have a clean vgrant box and this playbook fails with:
`TASK [habor : Commenting required line on Nginx configuration if harbor_behind_proxy is set] ***
failed: [debian-11] (item=nginx.http.conf) => {"ansible_loop_var": "item", "changed": false, "item": "nginx.http.conf", "msg": "Path /opt/harbor/common/templates/nginx/nginx.http.conf does not exist !", "rc": 257}
failed: [debian-11] (item=nginx.https.conf) => {"ansible_loop_var": "item", "changed": false, "item": "nginx.https.conf", "msg": "Path /opt/harbor/common/templates/nginx/nginx.https.conf does not exist !", "rc": 257}`

**Comment by bodsch** [comment]
hi @huckley ! 
Does your problem still exist, or can I close this issue?
